library(dplyr)
library(tidyr)
path1<-file.path("train","subject_train.txt")
path2<-file.path("train","X_train.txt")
path3<-file.path("train","Y_train.txt")
path4<-file.path("features.txt")
path5<-file.path("test","X_test.txt")
path6<-file.path("test","Y_test.txt")
path7<-file.path("test","subject_test.txt")
path8<-file.path("activity_labels.txt")



features<-read.table(file=path4,header=FALSE,col.names = c("no","Feature"))
features<-tbl_df(features)
features<-features[,2]
colnames<-features$Feature
X_Train<-read.table(file=path2,header=FALSE,col.names = colnames)
X_Train<-tbl_df(X_Train)
X_Test<-read.table(file=path5,header=FALSE,col.names = colnames)
X_Test<-tbl_df(X_Test)
Y_Train<-read.table(file=path3,header=FALSE,col.names = "Activity_Code")
Y_Train<-tbl_df(Y_Train)
Y_Test<-read.table(file=path6,header=FALSE,col.names = "Activity_Code")
Y_Test<-tbl_df(Y_Test)
Subject_Train<-read.table(file=path1,header=FALSE,col.names = "Subject")
Subject_Train<-tbl_df(Subject_Train)
Subject_Test<-read.table(file=path7,header=FALSE,col.names = "Subject")
Subject_Test<-tbl_df(Subject_Test)
activities<-read.table(file=path8,header=FALSE,col.names = c("Activity_Code","Activity_Name"))
activities<-tbl_df(activities)
names(X_Train)
Xsubset<-select(X_Train, contains(c("mean","std")))
names(Xsubset)
X2subset<-select(X_Test, contains(c("mean","std")))
X_Data<-bind_rows(Xsubset,X2subset)
Y_Data<-bind_rows(Y_Train,Y_Test)
Subject_Data<-bind_rows(Subject_Train,Subject_Test)
X_Data<-bind_cols(X_Data,Subject_Data)
TidyData<-bind_cols(X_Data,Y_Data)
TidyData<-merge(TidyData,activities)
TidyData<-TidyData[,2:89]
names(TidyData)<-gsub("Acc","Accelerometer",names(TidyData))
names(TidyData)<-gsub("Gyro","Gyroscope",names(TidyData))
names(TidyData)<-gsub("BodyBody","Body",names(TidyData))
names(TidyData)<-gsub("Mag","Magnitude",names(TidyData))
names(TidyData)<-gsub("^f","Frequency",names(TidyData))
names(TidyData)<-gsub("^t","Time",names(TidyData))
names(TidyData)

TidyData2<-group_by(TidyData,Subject,Activity_Name)
Final_Data<-summarise_all(TidyData2,funs(mean))
write.table(Final_Data,"Final_Data.txt",row.names = FALSE)
